require('plugins.configs.lualine')
require('plugins.configs.bufferline')
require('plugins.configs.hop')
require('plugins.configs.autopairs')
require('plugins.configs.treesitter')
require('plugins.configs.nvim-tree')
