require('plugins.configs.lualine')
require('plugins.configs.bufferline')
require('plugins.configs.hop')
require('plugins.configs.autopairs')
require('plugins.configs.treesitter')
require('plugins.configs.nvim-tree')
require('plugins.configs.trouble')
require('plugins.configs.nvim-comment')
-- require('plugins.configs.comment')
require('plugins.configs.telescope')
require('plugins.configs.nvim-surround')
require('plugins.configs.code-runner')
require('plugins.configs.null_ls')
require('plugins.configs.lsp')
require('plugins.configs.lsp-saga')
require('plugins.configs.cmp')
require('plugins.configs.darkplus')
-- require('plugins.configs.tokyonight')
require('plugins.configs.nvim-ts-autotag')
require('plugins.configs.nvim-web-devicons')
require('plugins.configs.luasnip')
require('plugins.configs.indent-blankline')
